// import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React, { useEffect, useRef, useState } from "react";
import DisplayMac from "../components/DisplayMac";

// const Home: NextPage = () => {
const Home = () => {
  const headerRef = useRef();

  function Header(props) {
    const [opacity, setOpacity] = useState(1);

    useEffect(() => {
      const headerHeight = headerRef.current.clientHeight;
      const range = 500;
      const offset = headerHeight / 1.8;

      const didScrollPage = (e) => {
        let calc = 1 - (window.scrollY - offset + range) / range;

        if (calc > 1) {
          calc = 1;
        }
        if (calc < 0) {
          calc = 0;
        }
        if (window.scrollY === 0) {
          calc = 1;
        }
        console.log(calc);

        setOpacity(calc);
      };

      window.addEventListener("scroll", didScrollPage);

      // return () => {
      //   window.removeEventListener("keydown", didScrollPage);
      // };
    }, []);

    return (
      <header ref={headerRef} style={{ opacity: opacity }}>
        <div className="flex justify-center h-[80vh]">
          <div className="w-[50%]">
            <h2 className="text-5xl my-5 font-semibold text-gray-300">
              Hi, I&apos;m{" "}
              <span className="text-gray-400 px-2 font-extrabold ">
                Steve Braco
              </span>{" "}
              ✌️
            </h2>
            <p className="font-aeonikLight text-3xl max-w-[490px] my-5 leading-normal text-gray-300">
              Vous pourrez trouver ici mes différents projets personnels,
              formations JavaScript.
            </p>
            <div className="space-x-3 pt-8">
              <button className="btn">Resume</button>
              <button className="btn">Voir Projets</button>
            </div>
          </div>
          {/* <img
        src="https://lts-studio.com/wp-content/uploads/2021/10/rocket.png"
        alt="rocket react"
      /> */}
          <Image
            className="animate-[wiggle_3s_ease-in-out_infinite]"
            width="400"
            height="400"
            objectFit="contain"
            // src="https://epicreact.dev/static/3e4d61a7372760d641994598a98fca6d/2710a/landing-rocket%402x.webp"
            src="/rocket.png"
            alt="logo"
          />
        </div>
      </header>
    );
  }

  return (
    <main className="p-8 pt-16 font-aeonik">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {/* <div className="flex justify-center h-[80vh]">
        <div className="w-[50%]">
          <h2 className="text-5xl my-5 font-semibold text-gray-300">
            Hi, I&apos;m{" "}
            <span className="text-gray-400 px-2 font-extrabold ">
              Steve Braco
            </span>{" "}
            ✌️
          </h2>
          <p className="font-aeonikLight text-3xl max-w-[490px] my-5 leading-normal text-gray-300">
            Vous pourrez trouver ici mes différents projets personnels,
            formations JavaScript.
          </p>
          <div className="space-x-3 pt-8">
            <button className="btn">Resume</button>
            <button className="btn">Voir Projets</button>
          </div>
        </div>
        
        <Image
          className="animate-[wiggle_3s_ease-in-out_infinite]"
          width="400"
          height="400"
          objectFit="contain"
          // src="https://epicreact.dev/static/3e4d61a7372760d641994598a98fca6d/2710a/landing-rocket%402x.webp"
          src="/rocket.png"
          alt="logo"
        />
      </div> */}
      <div>
        <h2 className="font-aeonik font-extrabold text-gray-400  text-center text-5xl py-3 pb-16">
          Projet Récent
        </h2>
        <DisplayMac />
      </div>
      <div>
        <h2 className="font-aeonik font-extrabold text-gray-400 text-center text-5xl py-3 pb-16">
          Les Derniers Projets
        </h2>
        <div className="relative rounded-xl overflow-auto">
          <div className="overflow-x-scroll flex space-x-4">
            <div className="flex-none w-[500px] h-[400px] bg-lime-500 rounded-xl overflow-hidden border border-gray-800">
              <Link href="/audiophile">
                <Image
                  src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxISEhUSEhIVFhUWFRAXFRUQEBUVFRUWFRUWFxUVFxUYHSggGBolHRUVITIhJSkrLi4uFyEzODMtNygtLisBCgoKDg0OGhAQGi0dHyUtLi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSsrLf/AABEIAK4BIgMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAACAQMEBQYABwj/xABHEAACAQIEAggDBQUFBgYDAAABAgMAEQQSITEFQQYTIlFhcYGRMqGxFEJSYsEHIzNyghWS0eHwY4OTorLxZXN0s8LDJCVD/8QAGgEAAgMBAQAAAAAAAAAAAAAAAAECAwQFBv/EADYRAAICAQMCAgcGBQUAAAAAAAABAhEDEiExBEFRkQUTImFxgfAGobHB0eEUMkJi8RUjU4LS/9oADAMBAAIRAxEAPwBxuhkwGkHsKiJ0XnclViNx3i1e7ZR3UKRKNgKpfT4/eeij9osiTuCPBpei+JVshVrnkKZxvQfEgXaM6+te+mBb3yi/lRNEDuB7VL1MF3ZGXp5y2eNV35Pno/szxTC/VaeYq74RwPiGDUBQ2XuDEkeVe22pr7Ot72qeiNctfMz4/SyhJy9XHc8znwnEZV7SuR+Zz9KzmO6HYu+Z1ue4G9e55RQGBSb2qHqYPd35lsPTs47LHFL3JnjeE6GYm1+q9zR4noTMw1i9jXsmUUtqj6jH7/P9iT+0Od/0x+8+Wek/Rhor6EEcjWM2r6X/AGqcOTqDLYAj9a+aZTdj61OEXFuN2Z/SMsWXHjzwjpcrTXbb/IOalzUNLVpyUgqE1wpGoHQl6Suq6wXClI/eZs9rhdMpHd33pCKZEJNgCT3AXPtS5Ttz7q164dFiWWJQpU5Xy31O4Ynex2qxwuHinSYZFZgqyqWAuBpnG3ifYUrA8/K0oWtJjuCh1V4QL5CWUbdlipI9QPeqFlsbHemFjTCmjT7U2woBsbrqU0NIQ4DSMa4ULUwBo1oQKU0gHQaOM1HBo0NAEkmmzQF669A0K1NkUjGlWgQNq6nK6gD7crqxGC6XO8hDlVXlb/OrnEcfRVJzp704pSVpm3J6Pz45KLW5fV1YrhfS4NIwZha/Zvzq3xXH1QZsy01HUrTTQsnQZ8c9DW5fV1ZXhfS1ZSQbDXTXcd9WGK42qLfMvvQo2rXBGfR5oT0SjuXVdWbwHShZLjQHzpeJdIurW4Iv3UadrtUP+Bz69Gnc0ddWf4b0hEo1IBoeLdIBEhsQTY7GjTtd7Ef4PNr0VuYj9tnGLRrEp01LeNtq+fL16P8AtHx5kUs51Ow8684tUITU7a448jX6Txfw/q8N8Rv5t/sJeuBpctdaps5iZwNKTSWpGpDJ/BoAWzsLhNbHYnlfwraYXCNjFuDaVSO0y2DjXKdviGg8qyfC0uFS+5JPd3AHTa9vY16h0byxIpsAbWFjfzPmTuajKVDjHUQ+F9FHRWWQizbgC23d4Vd8G6KRJmINsyMveLEHv8TerOfGoVvz/Wo0HEhcW9qzudSNEcaceCtm6INEjshJ/duutiLk30sBYE67ad9eZ9KsCVbNlIbXMLbjv00uO/mLdxr288XUaAketYXp1h0dM4Guu1rH/V/nV0ZplEsbR5Rmrr0LrY2rlqwrOakojQUAGKQilrloAJEpHWnFNC5pDGwKWuBrjQAgpaEUVAhKUClWjNADddRV1AHsk+JBGh+dUWP4gy7EnwNYdMU/42/vGp0LudyT61DD0TnKj0eX7QrRUINfMtm6SOD8PsaMdLG5q3q16rhgidaNeGE7Cuj/AKR7jmL091af833IvcD0lLH4TVzFxUtvf3rHRcPdTpepIWUcz71D/Rp9jZD7RP8ArV/CjZwT3PdUzrRzb3NeeSYyQffb3qtxPFJPxt71ly9A8ezZevtBjlzjfmj0+Xiapzt61QcV6XxKCM9z4G9eez4hm3YnzNQ5KoXT+LI5PTv/AB418W7+5fqWHGeKtO1ztyqAooBToq9JRVI4ebNPNNzm7bOtSEUVCTQVx5EtQsKKlUgEEi4BBI7wDqKSLXRb8AKlvJUHqTt9a3yqygD6cqq55evaGQ2YkhlyrbKiMNT3La3uKm8XxnV2AkCX3Yrma52Cj/W9ZJS178GiMPV2uScM4Gp96YaTtVmv7TLG32p2G1iuX61brjLjNYWAte9USi0zRGVosliY9q/uaj8ZDNAVHxAgAMbDtELqe7WsvLJHcsRNIL2srnQnUc603DM0kbKyuV0yibXZgbBvvA2q2C0qyib1PT+Z51xvhzYeZoy6PsQ8RJVgeYuAR3ajcVXCpfFZy8ztfTMwXwUGygelQxWxXW5ilVuuBa61dS2qREQ0NO2rslIBA1Ia4ijjWnQxq1IalPHUZhSEa39m3R5MbiistzFGhkcA2z9pVVCRqAS1zbkDXrHHeiOExEJiEMcZAPVtFGqFDyIsNRtcHevG+hPSRsBietylkZSkqA2JQkG68swIBF/LS9elY/8AahgljzRCSSQjSNo8ljyzsTYD+W9Xwca3K5J3seNYiJo3ZG+JWZT5qbH6U1mp3FzNI7SN8TszNba7Ek/WmbVQWnZq6ly11A6JqjWrrhy3Iqnj3q3wL2tXU9F163coy8F3ltVvwzDAmstiMYe+rbgvFLW1ruS6hPLpMc4urNV/Zw7qg8QwIGwqXHxUHnUTH48GtOPU3vwVxbsyHFFsTWfm3q94q9yTWekbWvPela17HRxcHEVHlqQdqjyVyWWALTooEFGKQCGhNE1IBQMJaRq46U2TQFm36BYlWR42+NAer1+4zKZFt4EA/wBVaF8J1gNxYi4DWF/K9eVI1tRuCCPMV6Ziscw0UXBF/fv8KyZ46Xa7mzp5alpfYrx0bUv2m5/dG1a7C8LjEZjyaEHXne2lZ3g3EgWWR2DItyVJsDoeXPWrFOnOHAazZApPYYa68hbeqrk+S+oriitToyucm7Ag6i4sf1q4lmXCRdaB/CBaym5JtpoarOKcZXERrMq5SikaE5iN9bafXeqXiONZsM5LEq6qBm0PaYA38talTclZBuKi2jDkUlqNhSVtOccKK1BajBpgctFehNDSGG1Ij2pabagbJJeoz1wauNAgkFOEUyrUWegAstIRRJROKBpjNLSUtBLUSFkqSMVaq0mkzGrceRwdoqassjiC1CmKZDoaahOlBiDTeWerVe4aUWsPGX76kf2ux51nAaXOa1x9I5UiHqolvicXeq4tc0xnNHFWXLmlkdsmlRI5Uy4p6mjVNjEUUVKK6kADUoFcaWmhjchoVFScNg5JnyRIzt3KPr3etbHhHQFlV5cYWUJhZ8SIYXXrHSK/ZMlmVM2ViLBtFO1GpcElCTVpbGHOnjW/xr2t5D6Uxwvo7hJUSUrIL5j1fXB1IBIF2yAk+Vql8RiuTas+ZpqjR06abG+B4C9x1hVNsoIHPcE6Xtfffwq0TguEOrS9q5vmhIb4b7FSd9NL1Q4DFkOybG2g76kS8QnUhV29f8apfO5qg1RL4rw+IIMrOefaOXv3QbeR17+VZXpFibBYRoAAx8hcL+vyq7xeJItmOpIsO+reToTHi+rJYq8qsqOlzlkVWKB1ZrMjZSvZykMynUXtZiW9mfO9qR5YxokWr/i/Q/FQZWCmaJ1zJJCpYEXKm43UgqQfLmKo4K0pp8GWUJRdSVAtHTZFTymlR5FqTIjBNOwrTTCnYWpDXJKEelR5kp/raYmagk0RbUVIKK1IrAorVwWnAtBJI5DSu1cRTLGkSkqQt66hrqZAKlFDRJTEPoabdqctTDGmgFrqG9dekAQFHHTa0YoAfJpu9Nl669IB8GpOBwMszZIkLnnbYDvZjoo86sOjHRuTFtfVYge1Jbf8qDm3yHyPqeE4VBGgijUIi6mx1JPNjuW86UpKPJKMXLg83wvQmd95Il8i7fRbfOtdgOhuBiiSSWOSez9XOGkZdWUsrxiMiwIWQAEntKu96lxSRqz2Og01I99anYLFdZFiUAuTh3kUfikw5WdAP7jD+qq5SfCLsMYppz47/Dh/OrI2Owy4ZnhjCBQbqUUKrKwBR9N7qQfWpcWKtHBibZuoYwzqBctDJ1hX3EmIjH5mSoHFXzQ4Zv8AZyQ+f2aV0Q/8NovlQ8JxSqxSS/VyKY5bbhWt2x+ZSFceKisSejJ7vpry5PVSg8/SpNe0uUu7Vxkl8d0vivAbwXC/s6tBfN1TOqtvmjvmifTkyFW9agYxSDV91TAPG1uuw4KOBaz4cEFHUDkmdbf7OWM8jVfiYCRca1bO7PPRVOvD79tn81uZHiGFzG40YbGo4nxA00PiausZF2rc6jyYci2lRU3xRLSuVsRsDhmLh5DduXcK9N6NTgdWW0CFnuf9mjSMfZDWQ4Zw9m15VqAoigZrXMgMEagXLF7CYqN7iO6A/imUc6tg33KpQ1eyuXt5iyErg8ONiEmNv5ZnX6oaqeKdHMJPC0zR5ZS8YEiHKe1DiGOYfC2sa6kX03q44pLZ+pJBMMSxMRsZBd5SP947j0qHHrgcQDurwj/3Y/8A7qojKsj+f3I9DPGp9LHUuZJ7/wB80/zp/Ex3SL9nOOwrOEUToHcK0J7ZAJsWjOoNuQzedYzH4WSJsssbxt+GWNkPswFfSfFsVnZxz7LD+pQw+tZ+fExzJaREcfejlUMptzsdj5V0Iyu0eRkqr3ngFFWx6e9GI8OVxGGv1DmxQkkwv+G51KnWxPl3VjTUgTFD0LGhtSmkScmxVo6bvS5qBbUPItOEVHSSjz0Ag3qO4p6mWFAWDXU5lrqYhunYqapyKgQ81R3p9zpUdqAEpaSlFABoKcamg1czUhgmrfo3wVsXMIxcKNXYfdUfqdh/lVRevUeh+FXDYcXIEkozOSNRcdhfCwPuTQ+ASLtZepURxLZUAVVVbimeMcTtGAoIvq1+VRMRxED4W+72v8PE3qixrSNc2LDx8apbt2XJNJ1uL9uJNgQNb633B3+ntWg6F42+NgDG+eRkPlIjIf8ArrHRKw9dLC/zFajotw5lxEEpPwywt3fC4PIVGTVqiUYvS0yesbfYI847UeIZf7+GhLf80be1VtXHE9IMSo+5j/0xaD/oHtVS8bKbMCDZW17mFwfDQismdVL5ft+R6v0dPVj37tvzqX5lrg53lyZWCYqGwhLEATIt7QMW0DjMwXN2WDFDa4IkQxiYkQrklGbPh2BVww+IRhtXH5fjXmDuamLhcpXOUyxn78pCKfJzbN5LepYxaSEJiB1mXIBNEcsoCfDZ3W0ijWwkU25EVKE/ZqX19fP4bGTquijkk3hdvulVru+6VN29LcWnbi6uLPBcIfrCzqPHkR4WqVieEAnRQfM0/DxGZQAmOikHJOIQsGA7usySEn/ee1LLxPEc8Xg4R34WJnk9P3JP/OtT0xe9/h+pzXhyqWnS/Kf/AIvyTH2wiQRg4phGLErGlutkA3yKbZRsM7WUXFNYiV43E8qBJFUDDYcXtAu6ySA7ML5gG7TMczAWUCuXGRxEvEJJJSQWxGK1cEC2aNLtZtNHdnYcrUsSrKoZ5rMwlY52UkFUdhm1uSzAADU8zuLp5Eto/X7/AHfHtv6foNPtZU68K3fu9yfxtr2agrUosRtz15k71OwALQ4pO8YZ/SPF4cn5E0EfDUIH722oFuwSAdjo+o303201FP4bDdUJxnDF8NjLADZoo+t3BNwcoIPOqoY3qX1zsdLqeoj6qVcrfh/0tS/Im4jEEGM33gwZ874eL/OqTHgxtnHwsT6E8qseMPZIGG3URi//AJTPEdf93VbHjFYFTsdK0rI4ys8tPDcdHdbeWwgVJ0eGQXWRSCO48iPEGxHiK8m4pgXgleF/iQkeY+6w8CLH1r06aFoiGBut9D+hqg/aHAJEixSjUWjew3GpQ+mo9RWpNS3RhacXTMIaEmjNCRTEIBS5a5aNaBghaNFp1Vo8lABKtMSijZ7Uw73oAK4rqarqAOtTka1yinlFAgWFMstSDQkUAMEUNPMtCVoAbpaW1T+D8KkxMqwxC7HUk7Ko3Zj3CgAuj+A6+dEtdQcz6fcXU389B616BxHEAnVT5DY2qZheDwYSIxx6toXkb4nI527tdAP86jyxaEk2Gt7/AC+n1qqc/AthDxKiV77nQjYcuelQMTxEgWFBxTQDL+LSx86p53N6qas0JpLY1fR6FSM7m5OvkOVXL4++KwWFT4pcVhc1vuxiZSfex9FNYrgfFMpIY6KC3oNxU/oNi2fiIxb6iCPE4lvARQtkUf1GMVOEPat9irJk9mlyzdTyqYJpAoIkx6tY7MMs0xB8D9pUetScb0qUkvDhYkkNryyDrH23AIsDtrblVHMMmFwqX5TyWJ3zMIEY/wBGHv8A1VEjBJAFyTsALk+QrNkySTrjj9fzPT9N0mKcLlvTklu603p7bNNRXPYfxmMkmfPK7Mx5s1/+wpptNjRQQl1ZwyBVy5nlkjjRc18t2dgNbHQd1O4vDxRRdfLiEEZ6sK0AabOXMwAW1hvh5edtN6qUJy3Ss15OqwYPZlJRrt4fJfFdhkTnnRrN4U9khSN57SSxjCR4pVGSORs8kaZTcSBbB2J323pkzI8EGIiikjErTjLLIrn92VswZUTQ5+7lRLDOKcn2IY/SGDJkjii23JWtnVU3+CBlkYjup6HiEihQMtlta632frBf1+Wm1N4R16vESvHJIIYc+WKQIxtNDGxzZGsFWRmOnLlvRCWKSGKeFZUEjzKVmZGIMeTUMqgEHrO7lQoS06+w5dVheddPL+blbbcN8/CyUOLSWsQlrMP4etmYMbm9zqNO4aVO4RxDrMVF1gQKzuhyIq6YjsNe3IZ/SqaCN5GCIpZjsqAknmdBTDFlNjdWU7EEMpHeDqCKSlJNMtnhxzjKC2tNedq/huXE8zjBQ3FmilxEMg7mZUmt/eab2NZQ4y0nzrYcWcH7YALCWKHHIOQIYmf1vJi/SKvNsRKesIHI1slFPj6+keTyzfrG3y3fnu18na+KN5gsVnS1VfSFL4aZLfdLad6doH5U3wyQqtztRSSdasl+auLeBUj9aWG0/cV56a955uKUihFcTWwxiUqmutXCkIlxGnSaixtRF6BgzGmVonahWgQdq6hrqBjwo1psGjU0CDIoTRE0JoAE0NEaG1A0cF/0K9O6McP+xwkn+K4Bc93cnkPmb1muhfCOsczsLqmiC18z/i8l+vlWi4o8i/ce38t/pUJvwLIpErr2kawNhpcn6VD4zLlFl12zHkPL0vVXg3xDyWijdtd8tgPNjYD3rR4fgObXEOGY/wD8427Pq+59APOqWpcly09zG2eVgqKztrZUUsd97DW3jSz9E8c22Gb1eMfVq9Fwk0cLdXEqKoGgXv8A18zUz7b3keVRb0smlrR5fB0FxZtmMSd4aXMfH4AQfetX0f6JCGGdOvBknWJOsERskauJHQdrUOVS500XnetGZ/EUP2lebW8qbyuqQRwqLT8BjF8GDDTtrHHDHFGsgS6ogWzyFWI1F9F1zHUW1psVwvizq6wmHCqAMqYRnV5O0LZpyC5sNdXtpoNatcezr2onvpcpzPl303FxQzJYSMp11BNr9xXn5aGoRyaXfc0Ti8kFjlJ6UqrtS24/HuxzpVwhRg8Y7uGkaKCUoigBJIcpdiw0bMxfYD4qoOLIv9kZAosuD4fKp1JDnFNnYEnS5xU23JrVIxkhtiUJJtw+W5N7FxCrSMoJNgXVqiYls3DLf+F4c/3OIoP0q6Den/sU54+273vGn+FeSVFo2ILTlVNlbh7KFU2GR+HFwlh927Xt31XSyn7JgdSR9kSwvov72ZWsOROUe1TuFJebDfmwGFHvw9UqFwnCvNhcAEUsxw0ugsNExeL5nuA+VUzVwkv7jpdPpj1OB7JeqXu8d/uLzhPR52hZxLGplw+MjCMWH8aCSNLkC3xMpPdTOL4LilhwkLof3WHVdZUMaMJHz2Oa2oEe2+ndQxJPESjqQiKrNZlawkPYIZSRqT9a5sXI7ER7gDV3soF+83J57CqYyenQ0TzzlHqPXKSk624qnxwGvAGMM8bzpEZo1QMpZyB1sbuCBa4KoykX1vR4HhjZVgkxKYztxgGVGinjjJs3VTl2uBcNkcEdmwteobYct/GnI8IFH/U1/pUnC8Tw0FrRg2+9J2ifEk1bGWlaexhyuWTJ622peK2I+GkBManURTtA17C8GKDRsW77ESf8avOeFsetPWfECQ1+8aH6V6xxHDpiUaWABJXCHmqyZJEcX/N2CL+Ovh5dxfDNDjpkYEfvZGW/NGYlWHeCCKugvYr6+uDP1ORTyqa2+rf3tv5my4e8bLe2o0OnmPXe9SEwBMgyjfQj9KpeC4jtC53BG+vK4HdV3hsWEYNcgjcbk5Ta99NxY60sT3oqzLazzfj3Cmw07wsD2T2b80Oqn2+YNV2WvUOnSJiolmAtJFofzId/bQ+/fXns0Nq1IzcEQLQstO2oSKdDBUUuSlWn1FIVkNkrkWpUi0yBSEdlrqKuoGNmjQ0JpUoEOGkpa40AAxqx4Fw37RMsdyF1LkbhRvbxOgHnVawrf9FOGdTAJW+OUA/yp90eo19fCoydKyUI26NbhEjRFjjUIq2CgDS36nxp68fMj3qglnbloB86rZ5zVWqy/RXBpsZxVU7K2HzB86q24idcuhHI/Xy1qlEg7v73P2os5FyDvfT6iq5TJqBc4SULmPNrHNvrrSLiCNdTbx38RfeqOfG9UpcmwAHm3l41SYbpNKrlns6HdDYWH5WtcGoxhKdtFkpwgkj0CPFk/CCPFth/jS9ctv3lySPxfQioPC50a2VzqbZJNCD3DkfenuJJm+JCLc13FVOS4NLxyj/MhoI4GaO7i/IjOvod6j43EdlpVHbCm4IKliBezKefia5s8alrh0F7lDZwPFefpTeI6ycAxRmVgpFlIUFTzd20VVPMkWBO1OKt1/gUqStv9UTYG63DzSWIH2LGMpcWLB8PIQB36C/pVWnFcOOHBGnTrGwMsAhUO0gcY15VLWXKi5Qp1YHXanZcT1TwiMpJ1MEcDE9qKS6sJl5XQ9Y6X0uBcWo8J9nQ/uMFCh/HOGxLjut110FvBL+NXQnCCae9MlLoeoyuMo0tUd77W7a8fJMv+DqVWCURPJLHw2KRIluGZ0hsq2AJ1XW1tiKouEnHJhUw44TiHZIcTCJXTEIuSczZiUKBbgTtu3IUc+IdnLl2LMSWa5zMTvqKYllO7Xv+Y3qCzrf2e9/Wxtl6KnLT/u1UVHi/G+65s0EQnhwoi6lnlXhsZMCav1iYgxLooa+VGLlbaheW9Z3hHFM8ax5yZgGVw57SsLlrqTcLc8tr00ZDe4JBBBBBsQe8Hkask43ISDMEnsLAzpmcDmBMCJQPDNaovLGV2q3v9hT9GZI1okpUkqar5rlX9WHJGlhmZ2sLHJ2FPeeZHvUY4mCPRVS4/E2dv+Yk1IiiE8w6tVUnKI45Hut9jlL2BYnkdddL0ULCVzGrx51zZoxZZAV+IFDZhaxvpS7GOeOUJaJKn4NoteHcTeRA2U2GmulxUjiEMOKj6udM34GGjoe9W5H5HneoCmWJSpF7235VGGOKte3OpxyJIzzxNvgpuJcGfCHP/EiuCrgarfTtryPjt9KcSZWa5taw52129tK0MfGF1BF1NwwIvvuLcxrtVZiuiRl7eDkTKT/CkYjL4K+tx4HbvNXqP9UTM5cxmdFiEYFSBqLW7wd6wfEFyOyHdSR7Het7hOjeKjNnj070YN8gb/Ksj01whixAJFs6g/1L2T8svzq6JnZn3FAady001SsBC1OpJTBrhQIdkkptWoDRAUhpWHmrqGuoHpY80Bolw5q0kiFOxQCpURKjqTQmM1dtAKjyxgUmgKow9+nj3V6rPYC21rAeQ0FeayrcVusNijNAj7FlAP8AMNL+VU5eEaMK3aCxE2h+v+vSqrED6VOycjXLFsDWbUadNkFEIt/idKkNGbknYAanbQamp0eEHP61muO8X6xmhQFVU2Yndj3abL9aIJzlSCbWONsrOLYkyt+UfCP/AJW76qsl2C95A9zarFtqZwiXmj/nT5EH9K3UorYwq8k0n3aXmazCj+J+VyfQ/wDY1O+1AbE38zVXHLq/iDQpJcA92npXJo905JKiRFxAZn6zMVKsF6vKGDXFtSLbX3B32NC2NJXq0URxXvkjvZj+KRjrK/5mJ8LbVDhQXN9dTT1WXtRijghr9ZW/1x4BWtzq64LgusVpZXEWHi1lmfZRyRR99zsFHePAGjU3NqnftDlYRcPhBtEMIspjXRTK8koeQgbsQo1Pj3mp4oKbplPX9XLp8dw5bpe73lxwPE8Nxk6YaJscHkz5TKmHVOwjOb5STsp5VRxtmI9KZ/ZdpxXCfzyj3glFXPQwf/n4VTr++i8tG/yqWfHGNUq+kUei+ryzjklkk5aaa8pfjQ9jEwmCVRj+uaaQBhBhiivEh2aYyaBm5Jvbejx0WFfBx4vCrOoeWWIriHRiOrXMSMg7yOded47ENJLI7sWdncszG5JJNyTW8wJ//TYb/wBVjPotWZMUY43SMnSddnzdVHVJ03x244K99U9ak/2zIVIYI0hQx9c0YM4jOhiEm+QjTW5sSAQCRUYNdfWozGsSbXB6XLjhkrWk63V9mWGCJlxEEU0r9UzdodYwFghPI94FPY2NopXS9wtsp71OoPsflUXDDtB+YUgev/b505xHEEZWOv3fQbfU1dHfHRwetpdS/Cvr8RhZRY8idfPxFHheKSRm635bb71FY3rolzeFqsg9O5zprVsbbD9JSyjWxFgPbW4rP9N0GKiB06xLsjDdtO0h77gaeIFVUMhIp1ZiANdiD7a1oUjNKBkFS2hHvTUkYr6Y6Q9BMJOpvGoNtCBYj2rw/pt0WGCYFXzKToDuP8auZSY9o7VwWn964rSsZFNOIKGaiiNId0PZK6lzV1A9bP/Z"
                  width={500}
                  height={500}
                  alt="logo"
                  objectFit={"cover"}
                />
              </Link>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
};

export default Home;
